[package]
name = "cuckoo-service"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
cuckoo-core.workspace = true
cuckoo-macros.workspace = true
cuckoo-store.workspace = true
cuckoo-dto.workspace = true
cuckoo-http.workspace = true
cuckoo-flow.workspace = true
cuckoo-proxy.workspace = true
cuckoo-templates.workspace = true
cuckoo-ca.workspace = true
cuckoo-platform.workspace = true
sha2.workspace = true
ulid.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
axum.workspace = true
sea-orm.workspace = true
tracing.workspace = true
ts-rs.workspace = true
